version: '3.6'
services:
  dashboard-staging:
    container_name: dashboard-staging
    image: jerben/dashboard:latest
    build:
      context: ./board
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - HTTP_PORT=3000
      - ENV=STAGING
    ports:
      - 3000:3000
    command: ["java", "-jar", "dashboard-standalone.jar"]
