version: '3.3'
services:
  db:
    image: postgres:10.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db
  admin:
    image: microbox/pgweb
    ports:
      - 8080:8080
    environment:
      URL: postgres://admin:admin@db:5432/db?sslmode=disable
