version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Install some system dependencies
          command: sudo apt-get update -qq && sudo apt-get install -y ssh rsync
      - restore_cache:
          key: dashboard-{{ checksum "board/project.clj" }}
      - run: cd board && lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: dashboard-{{ checksum "board/project.clj" }}
      - run: cd board && lein uberjar
      - store_artifacts:
          path: board/target/dashboard-standalone.jar
          destination: uberjar
      - run:
          name: Move artifacts and Dockerfile to workspace
          command: |
            mkdir -p /tmp/workspace/board/target
            mv board/target/dashboard-standalone.jar /tmp/workspace/board/target
            mv board/Dockerfile /tmp/workspace/board
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - board

  release-stage:
    machine: true
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Release if tests pass and branch is master
          command: |
            mv /tmp/workspace/board .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build --pull -t jerben/dashboard:latest board
            docker push jerben/dashboard:latest

  deploy-stage:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy the docker images to staging
          command: |
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            ssh root@51.15.110.49 "mkdir -p /usr/share/docker/dashboard/ && rm -f /usr/share/docker/dashboard/docker-compose.test.yml"
            ssh root@51.15.110.49 "rm -f /usr/share/docker/dashboard/.env"
            ssh root@51.15.110.49 "echo DATABASE_URL=$DATABASE_URL > /usr/share/docker/dashboard/.env"
            ssh root@51.15.110.49 "echo DATABASE_NAME=staging >> /usr/share/docker/dashboard/.env"
            rsync -avz docker-compose.test.yml root@51.15.110.49:/usr/share/docker/dashboard/
            ssh root@51.15.110.49 "docker login -u $DOCKER_USER -p \"$DOCKER_PASS\""
            ssh root@51.15.110.49 "cd /usr/share/docker/dashboard/ && docker-compose -f docker-compose.test.yml pull && docker-compose -f docker-compose.test.yml down && docker-compose -f docker-compose.test.yml up -d"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - release-stage:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-stage:
          requires:
            - release-stage
          filters:
            branches:
              only: master
