version: "3.4"
services:
  traefik:
    image: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik-net"
      - "traefik.frontend.rule=Host:traefik.pillowboard.io"
      - "traefik.frontend.entryPoints=https"
      - "traefik.backend=traefik"
    command:
      - "--logLevel=DEBUG"
      - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.httpChallenge.entryPoint=http"
      - "--acme.onHostRule=true"
      - "--acme.onDemand=false"
      - "--acme.email=josef@pillowboard.io"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=pillowboard.io"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  traefik-net:
    driver: overlay
