version: '3.4'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      mode: global
  portainer:
    image: portainer/portainer
    volumes:
      - portainer_data:/data
    networks:
      - traefik
      - webgateway
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.docker.network=webgateway"
      - "traefik.frontend.rule=Host:portainer.pillowboard.io"
networks:
  webgateway:
    driver: overlay
    external: true
  traefik:
    driver: overlay
volumes:
  portainer_data:

 docker service create \
    --name traefik \
    --constraint=node.role==manager \
    --publish 80:80 --publish 8080:8080 --publish 443:443 \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --network traefik-net \
    --label traefik.frontend.rule=Host:traefik.pillowboard.io \
    --label traefik.port=8080 \
    --label traefik.frontend.entryPoints=https \
    traefik \
    --logLevel=DEBUG \
    --entrypoints="Name:http Address::80 Redirect.EntryPoint:https" \
    --entrypoints="Name:https Address::443 TLS" \
    --defaultentrypoints=http,https \
    --acme \
    --acme.storage=acme.json \
    --acme.entryPoint=https \
    --acme.httpChallenge.entryPoint=http \
    --acme.onHostRule=true \
    --acme.onDemand=false \
    --acme.email=josef@pillowboard.io \
    --docker \
    --docker.swarmMode \
    --docker.domain=pillowboard.io \
    --docker.watch \
    --api
